#define NPROC        64  // プロセスの最大数
#define NCPU          8  // CPUの最大数
#define NOFILE       16  // プロセスごとのオープンファイル数
#define NFILE       100  // システム全体でのオープンファイル数
#define NINODE       50  // アクティブなiノードの最大数
#define NDEV         10  // メジャーデバイス番号の最大数
#define ROOTDEV       1  // ファイルシステムのルートディスクのデバイス番号
#define MAXARG       32  // execの最大引数数
#define MAXOPBLOCKS  10  // 任意のFS操作が書き込む最大ブロック数
#define LOGSIZE      (MAXOPBLOCKS*3)  // オンディスクログ内の最大データブロック数
#define NBUF         (MAXOPBLOCKS*3)  // ディスクブロックキャッシュのサイズ
#define FSSIZE       2000  // ファイルシステムのサイズ（ブロック数）
#define MAXPATH      128   // ファイルパス名の最大長
