// System call numbers
#define SYS_fork    1   // プロセスのフォーク
#define SYS_exit    2   // プロセスの終了
#define SYS_wait    3   // 子プロセスの終了を待つ
#define SYS_pipe    4   // パイプの作成
#define SYS_read    5   // ファイルの読み込み
#define SYS_kill    6   // プロセスの強制終了
#define SYS_exec    7   // 新しいプログラムの実行
#define SYS_fstat   8   // ファイルのステータス取得
#define SYS_chdir   9   // カレントディレクトリの変更
#define SYS_dup    10   // ファイルディスクリプタの複製
#define SYS_getpid 11   // プロセスIDの取得
#define SYS_sbrk   12   // メモリの拡張
#define SYS_sleep  13   // プロセスのスリープ
#define SYS_uptime 14   // システムの稼働時間の取得
#define SYS_open   15   // ファイルのオープン
#define SYS_write  16   // ファイルへの書き込み
#define SYS_mknod  17   // 特殊ファイルの作成
#define SYS_unlink 18   // ファイルの削除
#define SYS_link   19   // ファイルのリンク作成
#define SYS_mkdir  20   // ディレクトリの作成
#define SYS_close  21   // ファイルのクローズ
